import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import HeaderApp from "@/components/header-app";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
});

const caveat = Caveat({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-caveat"
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "To Do App | Fernando Oviedo",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="es" suppressHydrationWarning>
                <head>
                    <script src="https://unpkg.com/react-scan/dist/auto.global.js"></script>
                </head>
                <body className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased`}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <div className="min-h-screen w-screen h-screen bg-background py-4 px-4">
                            <HeaderApp />
                            {/* Content */}
                            <div className="max-w-4xl mx-auto">{children}</div>
                        </div>
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}
